{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-webview/0.1.0/compose-webview-0.1.0.module",
    "group": "io.github.gycrosskit",
    "module": "compose-webview",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-webview-iosArm64Main-0.1.0.klib",
          "url": "compose-webview-iosarm64-0.1.0.klib",
          "size": 229104,
          "sha512": "7a2491754487b9c2bd1f09a83a4c3b26994e16a0cbaac4921ac39f8409ab53310aae9a3726312d927f959b22a79cc92c2ebf7674f736f937bf093b49bc745ef9",
          "sha256": "558f93cab326ef66110f1c5413ae52ed12582f67647be7a0435e578aeca840f2",
          "sha1": "39058d86240621d3b9308d1208f39fddfbd7a48b",
          "md5": "590bb2688346b0f0fa2ff6525c542d86"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "compose-webview-iosarm64-0.1.0-sources.jar",
          "url": "compose-webview-iosarm64-0.1.0-sources.jar",
          "size": 41735,
          "sha512": "a45be2b16cdb24fc70eb0105c5ef2f375c0dea808230069e8ca95ceeb0de4432bf35541666df31dc7fc3e8c4ee7b3a6d0c529c704555ce142f163da598e4e3ff",
          "sha256": "e3f0e4df523b085035f2438b3f3e3cfd683d4e788db234e9b400fb9f2042e510",
          "sha1": "c1ece382ee247666903dd6d7c44a39693a0e6902",
          "md5": "a1cad0a779d269dc16bc1c04227a3333"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-webview-0.1.0.kotlin_resources.zip",
          "url": "compose-webview-iosarm64-0.1.0-kotlin_resources.kotlin_resources.zip",
          "size": 360,
          "sha512": "faf665e5f0da98c16b9ffb364d0cbe2d57102f0bd2fae397e9d11a1bfc909d837b55563e22d6beca9a54be75b09181818652692f4df07b65160f804f91768299",
          "sha256": "3132fc2935425505dcceb643da4b2c0da8b902b6106dc07a5629797014aa943a",
          "sha1": "eb2465ea4058a1924e3f399e6ef9656549134815",
          "md5": "14b71ca1b1517e73a21d76603f8b488d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-webview-iosarm64-0.1.0-metadata.jar",
          "url": "compose-webview-iosarm64-0.1.0-metadata.jar",
          "size": 13337,
          "sha512": "82ad63383bf0f0091818f97a85e191172963ba4ddfcb4325985d0136034c4cc1fd268914f9fe20c1bda60f5800cef9a362aa17e194aeafe4affc8eb0cd00b1ac",
          "sha256": "96ac0e4f4b3722cb5889708707b226b53ee4f3304904479149df306b58a1000a",
          "sha1": "ac814f82e36443846506743da4ba21d7f8c1f1ec",
          "md5": "9654fca259ba626f6fc0cb551907f654"
        }
      ]
    }
  ]
}
