{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-webview/0.1.0/compose-webview-0.1.0.module",
    "group": "io.github.gycrosskit",
    "module": "compose-webview",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-webview-iosSimulatorArm64Main-0.1.0.klib",
          "url": "compose-webview-iossimulatorarm64-0.1.0.klib",
          "size": 229170,
          "sha512": "335e8d6f1de1d8a8a0a46b8a46e4660aea53b522d1d05f7d211f46467024be679d3406839910aa66ba6c4b914c556e754f992005a71d9a6e02e4f48d4c500093",
          "sha256": "46e4dfe71bc5265fc25f7fffff86ee668af6cafa1bdd8ae2159b12cbb991e2b6",
          "sha1": "8e1675eba6e968f76bf1828756a33ce5bd17d8e1",
          "md5": "26ef3145c0af3b84a22c2a3341119f74"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "compose-webview-iossimulatorarm64-0.1.0-sources.jar",
          "url": "compose-webview-iossimulatorarm64-0.1.0-sources.jar",
          "size": 41735,
          "sha512": "a45be2b16cdb24fc70eb0105c5ef2f375c0dea808230069e8ca95ceeb0de4432bf35541666df31dc7fc3e8c4ee7b3a6d0c529c704555ce142f163da598e4e3ff",
          "sha256": "e3f0e4df523b085035f2438b3f3e3cfd683d4e788db234e9b400fb9f2042e510",
          "sha1": "c1ece382ee247666903dd6d7c44a39693a0e6902",
          "md5": "a1cad0a779d269dc16bc1c04227a3333"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-webview-0.1.0.kotlin_resources.zip",
          "url": "compose-webview-iossimulatorarm64-0.1.0-kotlin_resources.kotlin_resources.zip",
          "size": 360,
          "sha512": "f4259f6cde7fad4e8127e97fbd8b99b87faebd9e2eb242f13f3ecb503cb48c91f63836834bc077a2292f181dee2de1c235a530fd55ebef8d942a194bc1347e54",
          "sha256": "217f90e24b1f764d0976587d4658c97957f657bc03c4941f69aac21354704ccd",
          "sha1": "4be3de479de85a42f7f5ffa27024366904f2bff6",
          "md5": "e4af6845a027323f90f129b0855fc1a9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-webview-iossimulatorarm64-0.1.0-metadata.jar",
          "url": "compose-webview-iossimulatorarm64-0.1.0-metadata.jar",
          "size": 13337,
          "sha512": "c1a30c823130447a87c975aa071e2d60deb883a81352140f36238f165c1382d0a633577f8f3c3767b4295416d6990350434bf33f2a53a0a95f3624416963e506",
          "sha256": "9d28daa952e33a1c61afa5574b3e4902345c3a4b0a93fcf2360735f6e6eacf75",
          "sha1": "59769b261c9c3048badb1751e164cc48c452f9f4",
          "md5": "ec71976991b7b822287f49dba7acfb2d"
        }
      ]
    }
  ]
}
