{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-webview/0.1.0/compose-webview-0.1.0.module",
    "group": "io.github.gycrosskit",
    "module": "compose-webview",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-webview-iosX64Main-0.1.0.klib",
          "url": "compose-webview-iosx64-0.1.0.klib",
          "size": 229091,
          "sha512": "8aaf885c818b8b7a7b56da8bc02754b9983f172349b2f3f5599b69d85d3c5c53830895b51b7d9b0c4b5d4e07fae4672c2f9f75883b66e03319f3a0344c22486c",
          "sha256": "26f5eb8dfe42fe6600c8246dacdbdb2cd4418af7fcf5a5657b5a6c960b762227",
          "sha1": "0a73072fb154e6466cdc7f7c7b57aa2d61f39aa8",
          "md5": "56496442174d65944b5ef8cb755f57f6"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "compose-webview-iosx64-0.1.0-sources.jar",
          "url": "compose-webview-iosx64-0.1.0-sources.jar",
          "size": 41735,
          "sha512": "a45be2b16cdb24fc70eb0105c5ef2f375c0dea808230069e8ca95ceeb0de4432bf35541666df31dc7fc3e8c4ee7b3a6d0c529c704555ce142f163da598e4e3ff",
          "sha256": "e3f0e4df523b085035f2438b3f3e3cfd683d4e788db234e9b400fb9f2042e510",
          "sha1": "c1ece382ee247666903dd6d7c44a39693a0e6902",
          "md5": "a1cad0a779d269dc16bc1c04227a3333"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-webview-0.1.0.kotlin_resources.zip",
          "url": "compose-webview-iosx64-0.1.0-kotlin_resources.kotlin_resources.zip",
          "size": 360,
          "sha512": "02a4a3df3da4b115af86f97045d22dddba47b563246b06277a19df59a6eaa0e652e1e1b6621c4f751fa4c1198ee169137f8a3f09ff2f8d919ed2a3e1b7a5cb07",
          "sha256": "591a28486c74f4bad78c7057f38013f1ccc28abb32bf021eb171a17265baf37e",
          "sha1": "0122477a14125e9d1717cf5dc1f1218168dc1dd7",
          "md5": "b41f8603835d58d99bdc638ec976322d"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-webview-iosx64-0.1.0-metadata.jar",
          "url": "compose-webview-iosx64-0.1.0-metadata.jar",
          "size": 13337,
          "sha512": "58ce5d390fd845f0629da5679f9fbc86e78d4d6efe66d025ae9810e752233b435ae2972e2a572d84b780eddab0e8db1a0d39e412285ab23a73bf63cdde6b4258",
          "sha256": "7aedbd5b3c0fc90f9a1e2b2917177d4a556cd3613d09f09ddae9692ce7d4ee60",
          "sha1": "08effb881c1842d49037efbba517a2057a9a0bd5",
          "md5": "2618ad6de50216c5d1cd59ad40cca312"
        }
      ]
    }
  ]
}
